name: jupyanno
channels:
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - soumith
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - bokeh
  - SimpleITK
  - h5py
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - pytorch<0.5.0
  - torchvision
  - opencv3>=3.0
  - tensorflow
  - nbserverproxy
  - pymongo
  - pip:
    - keras<=3.0
    - plotly
    - bs4
    - seaborn==0.7.1
    - git+https://github.com/chestrays/multiappmode
    - cloudpickle
